### ISSUE TITLE
Redshift fails to access location services

### ISSUE THREAD

**Issue by etkeys** [etkeys/dotfiles-local#22]
When logging into any desktop session, *redshift* produces the failed to retrieve location information. The current redshift config uses manual mode, but the error is still present. Why didn't this happen when *aludra* was upgraded to 20.04?

Also, when logging in to i3 session, there are 3 instances of redshift running. One is from i3 config and there are two others that get restarted even after `kill -9`.

Right now, redshift has been uninstalled because the errors never go away and while the error message is present, the CPU is maxed out.

**Comment by etkeys** [comment]
Made some progress that seems stable

- Removed `exec --no-startup-id "sleep 3; redshift-gtk" from i3 config
- Removed `~/.config/autostart/redshift.desktop`

## Overcoming "failed to connect to geoclue-2.0"
1. Added `redshift` entry to `/etc/geoclue/geoclue.conf`. Did not work.
1. Added `exec --no-startup-id /usr/libexec/geoclue-2.0/demos/agent` to i3 config (thanks to [this comment](https://github.com/jonls/redshift/issues/318#issuecomment-407612769]))
2. Started `redshift` and `redshift-gtk` manually and no errors for geoclue-2.0, but now config file was not being read correctly.

## Overcoming "permission denied" when reading config file
1. Tried these locations for config, all resulted with `fopen: Permission denied`
  - `~/.config/redshift/redshift.conf` (v1.12 preferred location)
  - `~/.config/redshift.conf` (v1.11 preferred location)
  - `~/redshift.conf` (tried with `-c` option)
  - `/etc/redshift.conf` (v1.11 and v1.12 system default, if present)
2. Found [this thread](https://github.com/jonls/redshift/issues/408) which suggests that the changes in v1.12 do not play nicely when app is packaged by distros.
  - Suggested work around was to use the preferred location in v1.11, `~/.config/redshift.conf`. I tried this but still didn't work.
3. Still based on the same thread, decided to compile from source
  1. uninstall `redshift`
  2. Added the following packages
    - autopoint
    - intltool
    - libdrm-dev
    - libxcb1-dev (already installed)
    - libxcb-randr0-dev
    - libx11-dev (already installed)
    - libxxf86-dev
    - libglib2.0-dev
    - libtool
    - geoclue-2.0
  2. Built `redshift` from [source](https://github.com/jonls/redshift.git), checked out to v1.12
  - Download and apply [Ayatana AppIndicator3](https://github.com/jonls/redshift/pull/757) patch
      ```sh
      curl -o 757.patch https://github.com/jonls/redshift/pull/757.patch
      git am 757.patch
     ```
  - Do the build
     ```sh
     ./bootstrap
     ./configure
     make
     sudo make install
     ```
  - During the build, `bootstrap` compailed about `configure.ac:15: error possibly undefined macro AC_PROG_LIBTOOL ...`. 
    - Thinking that some of the libraries needed for `autoconf` were not where they [were supposed to be](https://superuser.com/questions/565988/autoconf-libtool-and-an-undefined-ac-prog-libtool), created symlink `ln -s /usr/share/aclocal /usr/local/share/aclocal`. Did not work
    - Then tried installing `libtool`. That worked.
4. Restarted and redshift worked as expected. Except the indicator is not the same one that Ubuntu Mate uses.
  - It seams that compiling `redshift` from source added `~/.config/autostart/redshift.desktop` back. So there is no need to keep it in the i3 config?

## Todo
- [x] Update `packages.csv`
- [x] Remove redshift from `/etc/geoclue/geoclue.conf` to see if it is needed.
- [x] Create systemd service to start geoclue-demo-agent after geoclue-2.0.service
- [x] Add redshift as submodule. Add build steps.
- [x] Investigate how to restore app indicator icon to be the one that gets used when install from Ubuntu repo.
- [x] Determine if Ayatana AppIndicator3 patch needs is applicable to *aludra*.
- [x] Determine how to restore geoclue usage to *jet*. Converted to manual mode late last year due to geoclue connection error. Maybe starting the demo agent as a service will fix the problem?

**Comment by etkeys** [comment]
- Redshift does not need an entry in `/etc/geoclue/geoclue.conf`
- `redshift-gtk` is only started on first login. If I log out and log back in, `redshift-gtk` does not start.

## Todo
- [x] Get redshift to always start on every login.

**Comment by etkeys** [comment]
- To enable app indicators like the ones that are installed from the Ubuntu repo, need to call `./configure` with `--enable-ubuntu`.

**Comment by etkeys** [comment]
- Copied `redshift-gtk.service` from `redshift/data/systemd` after build to `~/.config/system/user/`. Updated restart elements under `Service` so app would restart correctly after first login.
- Removed starting `redshift-gtk` from i3 config.

**Comment by etkeys** [comment]
Everything appears fixed. Will push changes once other issues have been fixed.
